---
# setup disk for docker

- name: Partition /dev/xvdb
  command: parted -s /dev/xvdb mklabel gpt mkpart primary 1 100%

- name: Configure volume group
  lvg:
    pvs: /dev/xvdb1
    vg: vgdocker00

- name: Configure logical volume
  lvol:
    vg: vgdocker00
    lv: lvdocker00
    size: 100%FREE

- name: Make filesystem
  filesystem:
    fstype: ext4
    dev: /dev/vgdocker00/lvdocker00

- name: Mount disk to /var/lib/docker
  mount:
    name: /var/lib/docker
    src: /dev/vgdocker00/lvdocker00
    fstype: ext4
    state: mounted