---
# Configure disk and docker

- name: Checking if disk needs to be configured
  include: configure_disk.yml
  when: not item.value.partitions and item.key == "xvdf"
  with_dict: "{{ ansible_devices }}"