---
# Configure disk and docker

- name: Copy daemon.json to /etc/docker/
  copy:
    src: "{{ item }}"
    dest: /etc/docker/
    owner: root
    group: root
    mode: 0644
  with_items:
    daemon.json

- name: Checking if disk needs to be configured
  no_log: true
  include: configure_disk.yml
  when: not item.value.partitions and item.key == "xvdf"
  with_dict: "{{ ansible_devices }}"