---
# setup disk for docker

- name: Partition /dev/xvdf
  command: parted -s /dev/xvdb mklabel gpt mkpart primary 1 100%

- name: Configure volume group
  lvg:
    pvs: /dev/xvdf1
    vg: vgdocker

- name: Configure thinpool logical volume
  lvol:
    vg: vgdocker
    lv: thinpool
    size: 95%VG
    opts: --wipesignatures y

- name: Configure thinpoolmeta logical volume
  lvol:
    vg: vgdocker
    lv: thinpoolmeta
    size: 1%VG
    opts: --wipesignatures y

- name: Running lvconvert
  command: lvconvert -y --zero n -c 512K --thinpool vgdocker/thinpool --poolmetadata vgdocker/thinpoolmeta

- name: Applying metadataprofile
  command: lvchange --metadataprofile docker-thinpool vgdocker/thinpool

- name: Make filesystem
  filesystem:
    fstype: ext4
    dev: /dev/vgdocker00/lvdocker00

- name: Mount disk to /var/lib/docker
  mount:
    name: /var/lib/docker
    src: /dev/vgdocker00/lvdocker00
    fstype: ext4
    state: mounted