---
# setup disk for docker

- name: Copy docker-thinpool.profile to /etc/lvm/profile/
  copy:
    src: docker-thinpool.profile
    dest: /etc/lvm/profile/
    owner: root
    group: root
    mode: 0644

- name: Partition /dev/xvdf
  command: parted -s /dev/xvdf mklabel gpt mkpart primary 1 100%

- name: Configure volume group
  lvg:
    pvs: /dev/xvdf1
    vg: vgdocker

- name: Configure thinpool logical volume
  lvol:
    vg: vgdocker
    lv: thinpool
    size: 95%VG
    opts: --wipesignatures y

- name: Configure thinpoolmeta logical volume
  lvol:
    vg: vgdocker
    lv: thinpoolmeta
    size: 1%VG
    opts: --wipesignatures y

- name: Running lvconvert
  command: lvconvert -y --zero n -c 512K --thinpool vgdocker/thinpool --poolmetadata vgdocker/thinpoolmeta

- name: Applying metadataprofile
  command: lvchange --metadataprofile docker-thinpool vgdocker/thinpool
