---
- hosts: all
  gather_facts: no

  collections:
    - community.network

  vars_prompt:
    - name: "vlan_id"
      prompt: "Enter VLAN ID"
      private: no
    - name: "interface"
      prompt: "Enter interface"
      private: no
  
  tasks:
    - name: Add interfaces to VLAN
      edgeswitch_vlan:
        vlan_id: "{{ vlan_id }}"
        untagged_interfaces:
          - "{{ interface }}"
        state: present
        auto_exclude: true
      become: yes