---
- hosts: all
  gather_facts: no
  become: yes
  connection: network_cli

  tasks:
    - name: Create vlan
      community.network.edgeswitch_vlan:
        vlan_id: 199
        name: voice
        action: present