---
- hosts: all
  gather_facts: no

  collections:
    - community.network

  vars_prompt:
    - name: "vlan_id_add"
      private: no
    - name: "interface"
      private: no
    - name: "vlan_id_remove"
      private: no
  
  tasks:
    - name: Add interface to VLAN
      edgeswitch_vlan:
        vlan_id: "{{ vlan_id_add }}"
        untagged_interfaces:
          - "{{ interface }}"
        state: present
        auto_exclude: true
      become: yes

    - name: Remove interface to VLAN
      edgeswitch_vlan:
        vlan_id: "{{ vlan_id_remove }}"
        excluded_interfaces:
          - "{{ interface }}"
        auto_exclude: true
      become: yes