---
- hosts: all
  gather_facts: no

  collections:
    - community.network

  vars_prompt:
    - name: "vlan_id"
      private: no
    - name: "interface"
      private: no
  
  tasks:
    - name: Show interface
      edgeos_command:
        commands: show interfaces switchport {{ interface }}
      become: yes

    - name: Show vlan
      edgeos_command:
        commands: show vlan {{ vlan_id }}
      become: yes